### PR TITLE
Added OnLevel method to allow for configurable log level

### PR DESCRIPTION
**Pull request by dahankzter**
I do this in a custom middleware I have in my project but I thought why not use your published version. I do need to be able to switch levels however so did this.

What do you think?

### CODE REVIEW

**Comment by dahankzter** [comment]
Ping @appleboy would this be of interest?

**Comment by appleboy** [comment]
how to change log level?

**Comment by dahankzter** [comment]
Zap has an atomic level zapcore.AtomicLevel that can be changed runtime safely.

If you give the constructor in this patch a given level say DebugLevel it will only log on that level and combined with the AtomicLogger you can switch on and off that behaviour.

As for how you signal the app is up to the application creator. I often use a Nats channel or a Zeromq to broadcast changes like these but you could do whatever suits you I guess.

**Comment by dahankzter** [comment]
If you want to I can provide an example in the example directory as well.

**Comment by dahankzter** [comment]
I hope the example isn't too messy @appleboy does this work?

**Comment by dahankzter** [comment]
I really don't know why the check failed.

**Comment by dahankzter** [comment]
I have no idea what the check that fails mean:

<code>The command "embedmd -d *.md" exited with 2.</code>

**Comment by appleboy** [comment]
@dahankzter because you change the example code, please also update the readme.

see more detail about embedmd tool github.com/campoy/embedmd

**Comment by appleboy** [comment]
conflicts.

**Comment by appleboy** [comment]
fixed in #53

**Pull request closed without merging**
